sudo: required

env:
  global:
    - DOCKER_IMAGE_NAME=anybox/caddy
  matrix:
    - VERSION=0.11.00
    - VERSION=0.10.14
    - VERSION=0.10.12

services:
  - docker

install: true

# use a docker early version as multi stage docker build require
# docker >= 17.05
# https://docs.docker.com/engine/userguide/eng-image/multistage-build/
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - docker build --pull -t $DOCKER_IMAGE_NAME -f Dockerfile .
  - docker run -d -p 666:80 --name caddyserver -v "$(pwd)/:/etc/caddy/" $DOCKER_IMAGE_NAME

script:
  - docker ps | grep -q $DOCKER_IMAGE_NAME
  - ./test_caddy.sh

after_success:
  - if [ ! -z "$TRAVIS_PULL_REQUEST" ]; then echos "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USERNAME --password-stdin && docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$VERSION && docker push $DOCKER_IMAGE_NAME:$VERSION; fi
